#!/bin/sh

# teclado
#setxkbmap es
#setxkbmap latam
#setxkbmap -option caps:swapescape

# touchpad / mouse
#~/.mouse

# aplicaciones de dwm
#dwmblocks &
#nm-applet &
#picom &
#~/.fehbg
#unclutter &
#xrdb -merge ~/.Xresources

# window managers
#exec dbus-run-session bspwm
#exec dbus-run-session dwm
#exec dbus-run-session startfluxbox
#exec dbus-run-session i3
#exec dbus-run-session openbox-session

# desktop environments
#exec dbus-run-session startplasma-x11
#exec dbus-run-session startlxde
#exec dbus-run-session mate-session
#exec dbus-run-session startxfce4

# deskop environment
#exec kde5
#exec lxde
#exec mate
#exec xfce4
