#!/bin/sh

opciones="Dracula\nGruvbox\nMinimal\nNord\nOnedark\nCancelar"
selec=$(echo -e $opciones | dmenu -i -p "Selector de temas")
case $selec in
	Dracula) cp $HOME/.suckless/dracula $HOME/.Xresources
			 cp $HOME/.config/nvim/lua/themes/nvim/dracula.lua $HOME/.config/nvim/lua/themes/nvim/theme.lua
			 cp $HOME/.config/nvim/lua/themes/lightline/dracula.vim $HOME/.local/share/nvim/lazy/lightline.vim/autoload/lightline/colorscheme/theme.vim
		 	 xrdb -merge ~/.Xresources
			 ;;
	Gruvbox) cp $HOME/.suckless/gruvbox $HOME/.Xresources
			 cp $HOME/.config/nvim/lua/themes/nvim/gruvbox.lua $HOME/.config/nvim/lua/themes/nvim/theme.lua
			 cp $HOME/.config/nvim/lua/themes/lightline/gruvbox.vim $HOME/.local/share/nvim/lazy/lightline.vim/autoload/lightline/colorscheme/theme.vim
		 	 xrdb -merge ~/.Xresources
			 ;;
	Minimal) cp $HOME/.suckless/minimal $HOME/.Xresources
			 cp $HOME/.config/nvim/lua/themes/nvim/minimal.lua $HOME/.config/nvim/lua/themes/nvim/theme.lua
			 cp $HOME/.config/nvim/lua/themes/lightline/minimal.vim $HOME/.local/share/nvim/lazy/lightline.vim/autoload/lightline/colorscheme/theme.vim
		 	 xrdb -merge ~/.Xresources
			 ;;
	Nord)    cp $HOME/.suckless/nord $HOME/.Xresources
			 cp $HOME/.config/nvim/lua/themes/nvim/nord.lua $HOME/.config/nvim/lua/themes/nvim/theme.lua
			 cp $HOME/.config/nvim/lua/themes/lightline/nord.vim $HOME/.local/share/nvim/lazy/lightline.vim/autoload/lightline/colorscheme/theme.vim
		 	 xrdb -merge ~/.Xresources
			 ;;
	Onedark) cp $HOME/.suckless/onedark $HOME/.Xresources
			 cp $HOME/.config/nvim/lua/themes/nvim/onedark.lua $HOME/.config/nvim/lua/themes/nvim/theme.lua
			 cp $HOME/.config/nvim/lua/themes/lightline/onedark.vim $HOME/.local/share/nvim/lazy/lightline.vim/autoload/lightline/colorscheme/theme.vim
		 	 xrdb -merge ~/.Xresources
			 ;;
	Cancelar)
		exit 0 ;;
esac
